name: Publish to Nexus Repository

on:
  push:
    tags:
      - 'v*.*.*'  # v로 시작하는 시맨틱 버전 태그 형식으로 제한 (예: v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create gradle.properties from secret
        run: |
          echo -e "${{ secrets.GRADLE_PROPERTIES }}" > gradle.properties

      - name: Show created file (debug)
        run: cat gradle.properties | grep -v password

      - name: Publish to Nexus
        run: ./gradlew publish