name: Publish to Nexus Repository

on:
  push:
    tags:
      - 'v*'  # 태그가 v로 시작할 때 실행 (예: v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Create gradle.properties with secrets
        run: |
          cat > gradle.properties << EOF
          # Nexus 저장소 접근 정보 (CI/CD에서 생성됨)
          nexusUrl=${{ secrets.NEXUS_URL }}
          nexusPort=${{ secrets.NEXUS_PORT }}
          nexusUsername=${{ secrets.NEXUS_USERNAME }}
          nexusPassword=${{ secrets.NEXUS_PASSWORD }}
          
          # 인코딩 설정
          org.gradle.jvmargs=-Dfile.encoding=UTF-8
          EOF

      - name: Show created file (debug)
        run: cat gradle.properties | grep -v password

      - name: Publish to Nexus
        run: ./gradlew publish
